version: '3'

services:
  web1:
    container_name: web1
    build: ./web1
    networks:
      - webnet

  web2:
    container_name: web2
    build: ./web2
    networks:
      - webnet

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - 80:80
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - web1
      - web2
    networks:
      - webnet

networks:
  webnet:
    driver: bridge